### ISSUE TITLE
week4

### ISSUE THREAD

**Issue by at7211** [Lidemy/mentor-program-2nd-at7211#7]
# DOM

```Javascript
// 根據傳入的值，找到 DOM 中 id 為 'xxx' 的元素。
document.getElementById('xxx');

// 針對給定的 tag 名稱，回傳所有符合條件的 NodeList 物件 [註1]
document.getElementsByTagName('xxx');

// 針對給定的 class 名稱，回傳所有符合條件的 NodeList 物件。
document.getElementsByClassName('xxx');

// 針對給定的 Selector 條件，回傳第一個 或 所有符合條件的 NodeList。
document.querySelector('xxx');
document.querySelectorAll('xxx');
```

再來我們就可以先透過 document.querySelector() 方法來取得節點，然後修改 textContent 屬性：
``` javascript
<script>
  document.querySelector('#greet').textContent = 'Hello World!'
</script>
```

**Comment by at7211** [comment]
# CSS
可以透過『逗號』同時對不同id修改樣式，例如：
``` css
#email,
input[type="text"] {
    margin: 20px 30px;
    padding-bottom: 5px;
    border: none;
    border-bottom: 1px solid rgba(0, 0, 0, 0.2);
    font-size: 13px;
}
```

另外則可以透過 input[type="   "]{輸入css style ...}：修改input標籤裡的css樣式
